### ISSUE TITLE
Notebook/Script for feature extraction

### ISSUE THREAD

**Issue by alvarag** [cataand/tfg-paddel#17]
I have been checking the notebooks of the repository and I haven't found yet the code for feature extraction, i.e., the process of video reading, call tsfresh...

Is it in the repository?

**Comment by catalinsh** [comment]
In [this notebook](https://github.com/cataand/tfg-paddel/blob/main/notebooks/00-train.ipynb), for example, all of that is done in the get_data function which is defined [here](https://github.com/cataand/tfg-paddel/blob/main/paddel/src/paddel/preprocessing/data.py) in the library and branches out to different functions.

**Comment by alvarag** [comment]
I can see it now, nevertheless is important to have properly commented all the functions. Currently only some of the functions have comments
