### ISSUE TITLE
Add programmer's manual

### ISSUE THREAD

**Issue by catalinsh** [cataand/tfg-paddel#5]

**Comment by alvarag** [comment]
Some comments on the documentation

[memoriaAAG.pdf](https://github.com/cataand/tfg/files/10889461/memoriaAAG.pdf)

**Comment by alvarag** [comment]
More comments

[anexosAAG.pdf](https://github.com/cataand/tfg/files/11081596/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/cataand/tfg/files/11081598/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Comments on the documentation.  We can talk about them later.

[memoriaAAG.pdf](https://github.com/cataand/tfg/files/11199949/memoriaAAG.pdf)

[anexosAAG.pdf](https://github.com/cataand/tfg/files/11199948/anexosAAG.pdf)

**Comment by alvarag** [comment]
More comments:

[anexosAAG.pdf](https://github.com/cataand/tfg-paddel/files/11428805/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/cataand/tfg-paddel/files/11428806/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Comments on the main document

[memoria-AAG.pdf](https://github.com/cataand/tfg-paddel/files/11616201/memoria-AAG.pdf)

**Comment by alvarag** [comment]
And comments on the annexes

[anexosAAG.pdf](https://github.com/cataand/tfg-paddel/files/11616492/anexosAAG.pdf)

**Comment by alvarag** [comment]
More final comments

[memoriaAAG.pdf](https://github.com/cataand/tfg-paddel/files/11651595/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/cataand/tfg-paddel/files/11651596/anexosAAG.pdf)
